version: '3.8'

services:
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"  # Map host port to container port
    volumes:
      - mongodb_data:/data/db  # Mount a volume for data persistence

volumes:
  mongodb_data:  # Define the named volume for MongoDB data